### ISSUE TITLE
Speak CSS

### ISSUE THREAD

**Issue by CajSWehst** [CajSWehst/components-on-a-grid#1]
[wehrstedt-caj-wd2-week2-speak-css.m4a.zip](https://github.com/CajSWehst/components-on-a-grid/files/7220697/wehrstedt-caj-wd2-week2-speak-css.m4a.zip)
@thatkidmadrid

**Comment by thatkidmadrid** [comment]
Looks good and sounds good!

For some grid items you're using both the `grid-area` as well as the `grid-row/grid-column`
They're essentially trying to do the same thing - position the item on the grid - and whichever appears last in the css will be applied

nothing really more to say other than that- I can tell that you get what's going on, keep it up

See you in class
